package com.privacyguard.ai.domain.model

/**
 * Weekly privacy report generated by the reporting engine.
 *
 * Feature 6: Weekly Privacy Reports
 */
data class PrivacyReport(
    /** Unique report identifier */
    val reportId: String,

    /** ISO-8601 date string for the week this report covers */
    val weekStartDate: String,

    /** Unix timestamp when the report was generated */
    val generatedAt: Long,

    /** Overall privacy score for the week */
    val overallScore: Int,

    /** Score change compared to the previous week (positive = improved) */
    val scoreDelta: Int,

    /** Per-day permission usage data */
    val dailyUsage: List<DailyUsageData>,

    /** Apps that were newly installed this week */
    val newlyInstalledApps: List<String>,

    /** Apps that were uninstalled this week */
    val uninstalledApps: List<String>,

    /** Permission changes detected this week */
    val permissionChanges: List<PermissionChange>,

    /** Top 3 highest-risk apps */
    val topRiskApps: List<AppRiskSummary>,

    /** AI-generated recommendations (populated when AI is available) */
    val aiRecommendations: List<String>,
)

/**
 * Permission usage data for a single day.
 */
data class DailyUsageData(
    /** Day label (e.g. "Mon", "Tue") */
    val dayLabel: String,

    /** Unix timestamp for this day */
    val timestamp: Long,

    /** Number of times location was accessed */
    val locationAccesses: Int,

    /** Number of times camera was accessed */
    val cameraAccesses: Int,

    /** Number of times microphone was accessed */
    val microphoneAccesses: Int,

    /** Number of times contacts were accessed */
    val contactsAccesses: Int,

    /** Number of times storage was accessed */
    val storageAccesses: Int,
)

/**
 * Lightweight app risk summary for report inclusion.
 */
data class AppRiskSummary(
    val packageName: String,
    val appName: String,
    val privacyScore: Int,
    val riskLevel: RiskLevel,
    val topRiskReason: String,
)

/**
 * Security notification model.
 *
 * Feature 11: Security Notifications
 */
data class SecurityNotification(
    val notificationId: String,
    val type: NotificationType,
    val title: String,
    val message: String,
    val packageName: String?,
    val createdAt: Long,
    val isRead: Boolean,
)

enum class NotificationType {
    /** A high-risk app was detected or installed */
    HIGH_RISK_APP,

    /** A new dangerous permission was granted */
    DANGEROUS_PERMISSION_GRANTED,

    /** The overall privacy score decreased */
    SCORE_DECREASED,

    /** A new application was installed */
    NEW_APP_INSTALLED,

    /** A permission was changed (granted or revoked) */
    PERMISSION_CHANGED,

    /** Weekly privacy report is ready */
    WEEKLY_REPORT_READY,
}
